In [1]:
import numpy as np

In [4]:
arr=np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
arr[0]

0

In [6]:
arr[:5:2]

array([0, 2, 4])

In [7]:
arr<5

array([ True,  True,  True,  True,  True, False, False, False, False,
       False])

In [8]:
boolean=arr<5
boolean

array([ True,  True,  True,  True,  True, False, False, False, False,
       False])

In [9]:
arr[boolean]

array([0, 1, 2, 3, 4])

In [10]:
arr[arr<6]

array([0, 1, 2, 3, 4, 5])

In [12]:
arr[(arr>2)&(arr<9)]

array([3, 4, 5, 6, 7, 8])

Broadcasting#########################

In [13]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
arr*5

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45])

In [15]:
arr[:5]=99
arr

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9])

### slice of an array

In [17]:
arr=np.arange(1,10)
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
arr_slice = arr[:3]
arr_slice

array([1, 2, 3])

In [21]:
arr([-99,-99,-99])

TypeError: 'numpy.ndarray' object is not callable

ARRAY COPY##############

In [22]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [26]:
arr_copy=arr.copy()
arr_copy

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

#2-D ARRAY INDEXING

In [27]:
arr2d = np.arange(1,10).reshape(3,3)
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [28]:
arr2d[0]

array([1, 2, 3])

In [29]:
arr2d[1][1]

5

In [32]:
arr2d[:2:2]

array([[1, 2, 3]])

In [38]:
arr2d[0:2,1:]

array([[2, 3],
       [5, 6]])

In [43]:
arr2d[0:3,1]

array([2, 5, 8])

In [46]:
arr2d[:,1:2]

array([[2],
       [5],
       [8]])

In [48]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

##Fancy Indexing

In [51]:
arr2d[[0]]

array([[1, 2, 3]])

In [55]:
arr2d[[2,0]]

array([[7, 8, 9],
       [1, 2, 3]])

In [58]:
arr2d[[2,1,0]]

array([[7, 8, 9],
       [4, 5, 6],
       [1, 2, 3]])

## CREATING ARRAY FROM EXISING ARRAYS

In [60]:
arr=np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [62]:
arr1=arr[0]
arr1

array([1, 2, 3])

In [64]:
arr2=np.array([7,8,9])
arr2

array([7, 8, 9])

In [65]:
np.concatenate((arr1,arr2))

array([1, 2, 3, 7, 8, 9])

In [66]:
np.hstack((arr1,arr2))

array([1, 2, 3, 7, 8, 9])

In [67]:
np.vstack((arr1,arr2))

array([[1, 2, 3],
       [7, 8, 9]])

In [68]:
arr2d1=np.array([
    [1,1],
    [2,2]
])
arr2d1

array([[1, 1],
       [2, 2]])

In [69]:
arr2d2=np.array([
    [3,3],
    [4,4]
])
arr2d2

array([[3, 3],
       [4, 4]])

In [72]:
np.hstack((arr2d1,arr2d2))

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

In [73]:
np.vstack((arr2d1,arr2d2))

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

## BASIC NUMPY OPERATIONS

In [79]:
arr=np.arange(0,10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [76]:
arr_one=np.ones(10)
arr_one

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [81]:
arr_one=arr_one*5

## Arithmatic operations(+,_,*,/ )

In [82]:
arr+arr_one

array([ 5.,  6.,  7.,  8.,  9., 10., 11., 12., 13., 14.])

In [83]:
arr-arr_one

array([-5., -4., -3., -2., -1.,  0.,  1.,  2.,  3.,  4.])

In [84]:
arr*arr_one

array([ 0.,  5., 10., 15., 20., 25., 30., 35., 40., 45.])

In [85]:
arr/arr_one

array([0. , 0.2, 0.4, 0.6, 0.8, 1. , 1.2, 1.4, 1.6, 1.8])

## Univerrsal operations

In [86]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [87]:
np.power(arr,3)

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729], dtype=int32)

In [88]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [89]:
np.log10(arr)

C:\Users\sivav\AppData\Local\Temp\ipykernel_14132\2153533263.py:1: RuntimeWarning: divide by zero encountered in log10
  np.log10(arr)


array([      -inf, 0.        , 0.30103   , 0.47712125, 0.60205999,
       0.69897   , 0.77815125, 0.84509804, 0.90308999, 0.95424251])

In [90]:
np.log2(arr)

C:\Users\sivav\AppData\Local\Temp\ipykernel_14132\1405652587.py:1: RuntimeWarning: divide by zero encountered in log2
  np.log2(arr)


array([      -inf, 0.        , 1.        , 1.5849625 , 2.        ,
       2.32192809, 2.5849625 , 2.80735492, 3.        , 3.169925  ])

In [92]:
arr.max()

9

In [93]:
np.max(arr)

9

In [94]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [96]:
boolean=np.greater(arr,arr_one)
boolean

array([False, False, False, False, False, False,  True,  True,  True,
        True])

In [97]:
arr[boolean]

array([6, 7, 8, 9])

In [98]:
arr_one

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [99]:
arr[arr>arr_one]

array([6, 7, 8, 9])

In [100]:
np.unique(arr_one)

array([5.])

In [101]:
np.unique(arr)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [102]:
np.sort(arr)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [104]:
np.flip(arr)

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [105]:
arr[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [106]:
arr.ndim

1

In [107]:
arr.size

10

In [108]:
arr.shape

(10,)

In [116]:
arr.reshape(10,1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

## Sum of 2d array

In [117]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [118]:
np.sum(arr2d)

45

In [119]:
np.sum(arr2d,axis=0)

array([12, 15, 18])

In [120]:
np.sum(arr2d,axis=1)

array([ 6, 15, 24])

In [121]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [122]:
np.transpose(arr2d)

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [123]:
arr2d.transpose()

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [124]:
arr2d.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])